<a href="https://colab.research.google.com/github/ritik-hue/NLP-basics/blob/main/wordembedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent=['i really like food','its a glass of juice','watching movies is my therapy','mobile games are underrated']

In [3]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [4]:
voc_size=10000

one hot representation

In [7]:
onehotrep=[one_hot(words,voc_size) for words in sent]
print(onehotrep)

[[6377, 9975, 7520, 3796], [8552, 2602, 6725, 4182, 7056], [4209, 6277, 8373, 7116, 1299], [827, 9050, 352, 7598]]


word embedding representation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

making the sentences of equal size to make input size fixed

In [12]:
sent_length=6
embedded_docs=pad_sequences(onehotrep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 6377 9975 7520 3796]
 [   0 8552 2602 6725 4182 7056]
 [   0 4209 6277 8373 7116 1299]
 [   0    0  827 9050  352 7598]]


In [13]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 6, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 154ms/step


array([[-0.04128962, -0.02282007, -0.04271411, -0.03470641,  0.04538124,
         0.04452937,  0.04433485,  0.03145603,  0.00505112,  0.03616994],
       [-0.04128962, -0.02282007, -0.04271411, -0.03470641,  0.04538124,
         0.04452937,  0.04433485,  0.03145603,  0.00505112,  0.03616994],
       [-0.01622796,  0.03433919, -0.01247849, -0.02092258, -0.04134337,
        -0.0247698 , -0.0047699 ,  0.03825121,  0.00673337, -0.00334876],
       [-0.03650803, -0.02370903,  0.03431085, -0.00735049, -0.02894901,
         0.04239259, -0.02676398,  0.01615298, -0.0161861 ,  0.00442611],
       [-0.04050865,  0.01405606,  0.0259862 ,  0.01071442,  0.01334221,
         0.01710377, -0.02109835, -0.02613857,  0.04169753,  0.01467316],
       [-0.04308155, -0.00884246, -0.03724353,  0.03270953,  0.00075849,
         0.04049008, -0.00383123,  0.04983629,  0.03377027, -0.00277342]],
      dtype=float32)